name: Nuget
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: '3.1.x | 6.0.x'
            - run: dotnet build -c Release ecom-dotnet-sdk.sln
            - run: dotnet nuget push ./**/*.nupkg -k $ApiKey -s https://api.nuget.org/v3/index.json -n true
 