name: Test
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: |
                        3.1.x
                        6.0.x
            - run: dotnet test -c Release ecom-dotnet-sdk.sln
 